### ISSUE TITLE
Error when trying to run ./run-dapp.sh

### ISSUE THREAD

**Issue by BIR-Micah** [PegaSysEng/besu-sample-networks#79]
Hey PegaSys team,
 
Just trying out this walkthrough and getting stuck when trying to run the pet store example. I get the following error message:

./.common.sh: line 55: NO_LOCK_REQUIRED: unbound variable

guess it wasn't defined earlier? I updated .common.sh line 55 to just say if 1=0... got it to work but I'm not sure of what issues it could cause...

**Comment by joshuafernandes** [comment]
Hello @BIR-Micah 

Thanks for bringing this to our attention. #80 should fix that error

Cheers
